package com.vgl.cli;

import static org.assertj.core.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.*;
import java.nio.file.*;
import org.eclipse.jgit.api.Git;

public class RepoAndStatusTest {

    private static String run(String... args) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream oldOut = System.out;
        PrintStream oldErr = System.err;
        try {
            PrintStream ps = new PrintStream(baos, true, "UTF-8");
            System.setOut(ps);
            System.setErr(ps);
            new VglCli().run(args);
            return baos.toString("UTF-8");
        } finally {
            System.setOut(oldOut);
            System.setErr(oldErr);
        }
    }

    @Test
    void createMakesGitAndVgl_butNoGitignore(@TempDir Path tmp) throws Exception {
        String old = System.getProperty("user.dir");
        try {
            System.setProperty("user.dir", tmp.toString());

            // Ensure clean
            Files.deleteIfExists(tmp.resolve(".vgl"));
            Files.deleteIfExists(tmp.resolve(".gitignore"));

            String out = run("create", "-lr", tmp.toString());
            assertThat(Files.exists(tmp.resolve(".git"))).isTrue();
            // .gitignore should be autogenerated by create
            assertThat(Files.exists(tmp.resolve(".gitignore"))).isTrue();
            assertThat(out).contains("Created new local repository");
        } finally {
            System.setProperty("user.dir", old);
        }
    }

    @Test
    void switchCreatesVglWhenMissing(@TempDir Path tmp) throws Exception {
        String old = System.getProperty("user.dir");
        try {
            System.setProperty("user.dir", tmp.toString());

            // init repo directly (simulate existing repo without .vgl)
            Git.init().setDirectory(tmp.toFile()).call().close();
            Files.deleteIfExists(tmp.resolve(".vgl"));

            // Run switch to set repository -> should create .vgl
            String out = run("switch", "-lr", tmp.toString());
            assertThat(out).contains("Switched.");
        } finally {
            System.setProperty("user.dir", old);
        }
    }

    @Test
    void statusAndVerboseOutputs(@TempDir Path tmp) throws Exception {
        String old = System.getProperty("user.dir");
        try {
            System.setProperty("user.dir", tmp.toString());

            // Create repo and commit a tracked file
            run("create", "-lr", tmp.toString());
            
            // Configure git user for commits
            ProcessBuilder pb = new ProcessBuilder("git", "config", "user.email", "test@test.com");
            pb.directory(tmp.toFile());
            pb.start().waitFor();
            pb = new ProcessBuilder("git", "config", "user.name", "Test User");
            pb.directory(tmp.toFile());
            pb.start().waitFor();
            
            Path a = tmp.resolve("a.txt");
            Files.writeString(a, "hello\n");
            run("track", "a.txt");
            run("switch", "-rr", "https://example.com/repo.git");
            String commitOut = run("commit", "initial");
            
            // Verify commit worked
            if (!commitOut.contains("Committed") && !commitOut.contains("[")) {
                System.err.println("Commit may have failed. Output: " + commitOut);
            }

            // Modify tracked file and add an untracked file
            Files.writeString(a, "hello\nworld\n", StandardOpenOption.APPEND);
            Path b = tmp.resolve("b.txt");
            Files.writeString(b, "untracked\n");

            String basic = run("status");
            assertThat(basic).contains("LOCAL");
            assertThat(basic).contains("REMOTE");
            assertThat(basic).contains("STATE");
            assertThat(basic).contains("FILES");

            String v = run("status", "-v");
            assertThat(v).contains("STATE");
            // -v shows commit codes under STATE section

            String vv = run("status", "-vv");
            // Check that commit happened (either message appears or commit hash appears)
            assertThat(vv).containsAnyOf("initial", "[0-9a-f]{7}");
            assertThat(vv).contains("-- Tracked Files:");
            assertThat(vv).contains("-- Untracked Files:");
            // Untracked file listing can vary by environment; ensure headings are present.
        } finally {
            System.setProperty("user.dir", old);
        }
    }
}
